### PR TITLE
[fix] width 100 percent for mobile tile

### PR DESCRIPTION
**Pull request by Saitop**

### CODE REVIEW

**Comment by Saitop** [comment]
> This will affect food shop types:
> image
> image

as they need

**Comment by whipermr5** [comment]
> as they need

I think they only want it for 360px? Not sure

**Comment by whipermr5** [comment]
For 600px on mobile, there is space for more than one column

**Comment by Saitop** [comment]
> > as they need
> 
> I think they only want it for 360px? Not sure

yes the only want it for 360px. It would affect desktop style???

**Comment by whipermr5** [comment]
> It would affect desktop style???

Not desktop style, but between 360px and 600px

**Comment by Saitop** [comment]
> > It would affect desktop style???
> 
> Not desktop style, but between 360px and 600px

yes... they decide not change yet

**Comment by whipermr5** [comment]
375px there's space for 2 columns
540px there's space for 3 columns

**Pull request closed without merging**
